spring.application.name=eaic-erp
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/eaic_erp
spring.datasource.username=root
spring.datasource.password=20908113

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true